---
version: 3

# build_arg_defaults:
#   EE_BASE_IMAGE: 'registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:latest'
#   EE_BUILDER_IMAGE: 'registry.redhat.io/ansible-automation-platform-24/ansible-builder-rhel8:latest'
#   ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: '-cv'

# ansible_config: './ansible.cfg'
images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:latest'

dependencies:
  galaxy: ./requirements.yml
  python: ./requirements.txt
  system: ./bindep.txt

options:
  package_manager_path: /usr/bin/microdnf

additional_build_steps:
  #https://access.redhat.com/solutions/7024259 
  prepend_builder:
    - ENV PKGMGR_OPTS="--nodocs --setopt=install_weak_deps=0 --setopt=rhocp-4.12-for-rhel-9-x86_64-rpms.enabled=true"
  prepend_final:
    - ENV PKGMGR_OPTS="--nodocs --setopt=install_weak_deps=0 --setopt=rhocp-4.12-for-rhel-9-x86_64-rpms.enabled=true"
  prepend_base: |
    RUN whoami
    RUN cat /etc/os-release
  append_final:
    - RUN echo This is a post-install command!
    - RUN ls -la /etc
